//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChroniCalc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChroniCalc.ResourceData", typeof(ResourceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Templar&gt;
        ///    &lt;Redemption&gt;
        ///      &lt;Grace&gt;
        ///        &lt;effect&gt;7%,11%,15%&lt;/effect&gt;
        ///        &lt;duration&gt;4,4.50,5&lt;/duration&gt;
        ///        &lt;skill_requirement&gt;[284]&lt;/skill_requirement&gt;
        ///        &lt;x&gt;4&lt;/x&gt;
        ///        &lt;damage&gt;150%,150%,150%&lt;/damage&gt;
        ///        &lt;range2&gt;0,0,0&lt;/range2&gt;
        ///        &lt;family&gt;None&lt;/family&gt;
        ///        &lt;id&gt;285&lt;/id&gt;
        ///        &lt;range&gt;0,0,0&lt;/range&gt;
        ///        &lt;element&gt;Holy&lt;/element&gt;
        ///        &lt;value&gt;1500,2000,2500&lt;/value&gt;
        ///        &lt;proc&gt;500,600,700&lt;/proc&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string convertjson {
            get {
                return ResourceManager.GetString("convertjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;nodes&gt;
        ///  &lt;node&gt;
        ///    &lt;position&gt;1,1&lt;/position&gt;
        ///    &lt;ID&gt;20001&lt;/ID&gt;
        ///  &lt;/node&gt;
        ///  &lt;node&gt;
        ///    &lt;position&gt;2,1&lt;/position&gt;
        ///    &lt;ID&gt;20002&lt;/ID&gt;
        ///  &lt;/node&gt;
        ///  &lt;node&gt;
        ///    &lt;position&gt;3,1&lt;/position&gt;
        ///    &lt;ID&gt;20003&lt;/ID&gt;
        ///  &lt;/node&gt;
        ///  &lt;node&gt;
        ///    &lt;position&gt;4,1&lt;/position&gt;
        ///    &lt;ID&gt;20004&lt;/ID&gt;
        ///  &lt;/node&gt;
        ///  &lt;node&gt;
        ///    &lt;position&gt;5,1&lt;/position&gt;
        ///    &lt;ID&gt;20005&lt;/ID&gt;
        ///  &lt;/node&gt;
        ///  &lt;node&gt;
        ///    &lt;position&gt;6,1&lt;/position&gt;
        ///    &lt;ID&gt;20006&lt;/ID&gt;
        ///  &lt;/node&gt;
        ///  &lt;node&gt;
        ///    &lt;position&gt;7,1&lt;/position [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slot_ids {
            get {
                return ResourceManager.GetString("slot_ids", resourceCulture);
            }
        }
    }
}
